# Javascript Node CircleCI 2.1 configuration file
#
# Check https://circleci.com/docs/2.1/language-javascript/ for more details
#
version: 2.1
orbs:
    node: circleci/node@5.2.0
jobs:
    install:
        docker:
            - image: cimg/node:14.21.3
        working_directory: ~/repo
        steps:
            - checkout
            - restore_cache:
                keys:
                    - v1-dependencies-{{ checksum "package.json" }}
                    - v1-dependencies-
            - run:
                name: install dependencies
                command: npm ci
            - save_cache:
                paths:
                    - node_modules
                key: v1-dependencies-{{ checksum "package.json" }}
            - persist_to_workspace:
                root: ~/repo
                paths:
                    - node_modules
    test-snyk:
        docker:
            - image: cimg/node:14.21.3
        working_directory: ~/repo
        steps:
            - checkout
            - attach_workspace:
                at: ~/repo
            - run:
                name: test snyk issues
                command: npm run test-snyk
    test:
        docker:
            - image: cimg/node:14.21.3
        working_directory: ~/repo
        steps:
            - checkout
            - attach_workspace:
                at: ~/repo
            - run:
                name: install meteor
                command: curl https://install.meteor.com/ | sh
            - run:
                name: run tests
                command: npm test
workflows:
    build-and-test:
        jobs:
            - install
            - test-snyk:
                requires:
                    - install
            - test:
                requires:
                    - install
