# Javascript Node CircleCI 2.1 configuration file
#
# Check https://circleci.com/docs/2.1/language-javascript/ for more details
#
version: 2.1
orbs:
    node: circleci/node@5.2.0
jobs:
    install:
        docker:
            - image: cimg/node:14.21.3
        working_directory: ~/repo
        steps:
            - checkout
            - node/install-packages:
                pkg-manager: npm
            - persist_to_workspace:
                root: ~/repo
                paths:
                    - node_modules
    test-snyk:
        docker:
            - image: cimg/node:14.21.3
        working_directory: ~/repo
        steps:
            - checkout
            - attach_workspace:
                at: ~/repo
            - run:
                name: test snyk issues
                command: npm run test-snyk
    check-types:
        docker:
            - image: cimg/node:14.21.3
        working_directory: ~/repo
        steps:
            - checkout
            - attach_workspace:
                at: ~/repo
            - run:
                name: check types
                command: npm run check-types
    test:
        docker:
            - image: cimg/node:14.21.3
        working_directory: ~/repo
        steps:
            - checkout
            - attach_workspace:
                at: ~/repo
            - run:
                name: install meteor
                command: curl https://install.meteor.com/ | sh
            - run:
                name: run tests
                command: npm test
workflows:
    build-and-test:
        jobs:
            - install
            - test-snyk:
                requires:
                    - install
            - check-types:
                requires:
                    - install
            - test:
                requires:
                    - install
