# Javascript Node CircleCI 2.1 configuration file
#
# Check https://circleci.com/docs/2.1/language-javascript/ for more details
#
version: 2.1
orbs:
    node: circleci/node@5.2.0
    snyk: snyk/snyk@2.0.2
jobs:
    build:
        docker:
            # specify the version you desire here
            - image: cimg/node:14.21.3

            # Specify service dependencies here if necessary
            # CircleCI maintains a library of pre-built images
            # documented at https://circleci.com/docs/2.0/circleci-images/
            # - image: circleci/mongo:4.2

        working_directory: ~/repo

        steps:
            - checkout

            - run:
                  name: install meteor
                  command: curl https://install.meteor.com/ | sh

            # Download and cache dependencies
            - restore_cache:
                  keys:
                      - v1-dependencies-{{ checksum "package.json" }}
                      # fallback to using the latest cache if no exact match is found
                      - v1-dependencies-

            - run:
                  name: install dependencies
                  command: npm ci

            - save_cache:
                  paths:
                      - node_modules
                  key: v1-dependencies-{{ checksum "package.json" }}

            - snyk/scan

            - run:
                  name: run tests
                  command: npm test
